export type Post={
    id:number,
    color:string,
    title:string,
    info:string,
    content:string
}

export const posts: Post[] = [
    {id:0,color:"#b6ba36",title:"Por que PhP é uma boa para iniciantes?",info:"12/06" ,content: "Com 3 argumentos eu vou mostrar o porque de php ser uma das melhores linguagens para iniciantes. <br> <br> <br> <strong>1 - Cliente - Servidor:</strong> <br> <br> O PHP ao mesmo tempo que separa bem o backend do frontend, também facilita entender as funções de cada um, forçando um entendimento mesmo que básico sobre servidores, já que é necessário um para rodar a linguagem, como o Apache. <br> <br> O PHP elimina a necessidade de API 's para fazer a comunicação, utilizando de formulários para se integrar ao frontend, que facilita um pouco para iniciantes, que mesmo escolhendo apenas uma área, vai ter uma noção básica de como funciona o outro lado. <br> <br> <br> <strong>2 - Arquitetura de software:</strong> <br>  <br> O Laravel (maior framework de PhP), introduz dois conceitos de forma simples, tanto de executar, quanto de entender: MVC e Migrations. <br> <br> O MVC no Laravel é quase que auto explicativo para qualquer iniciante, graças a relação entre front e backend citada no tópico anterior. Este modelo de arquitetura de software é bem versátil e pode ser utilizada nos mais diversos projetos e linguagens, introduzindo 3 conceitos: <br> <br> <strong>. Model -></strong> Onde o software faz a conexão com banco de dados, onde fica a lógica por trás do software e onde as regras de negócios são aplicadas, sendo o backend do software; <br> <br> <strong>. View -></strong> É onde fica localizado o frontend, as páginas que serão exibidas aos usuários;   <br> <br> <strong>. Controller  -> </strong>Faz a conexão entre o VIEW e o MODEL, atuando como um negociador intermediário e garantindo uma comunicação eficiente entre ambas as partes. <br> <br> Já as Migrations são uma excelente forma de manter o controle do banco de dados na hora de desenvolver, além de ser uma documentação para o mesmo, as Migrations permitem ter um controle de versões, podendo fazer e desfazer alterações no banco de dados de forma fácil. <br> <br> <br> <strong>3 - Frameworks:</strong> <br> <br> Como já citado no tópico anterior, o PHP conta com um dos melhores frameworks do mundo de desenvolvimento: o Laravel; que além do MVC, conta com um ótimo router e um ORM sensacional, facilitando o acesso ao banco de dados. <br> <br> Também existem outras excelentes opções, como o CakePHP, que tem uma curva de aprendizado suave e contém muitos recursos de forma nativa (como recursos de segurança), e o framework Symfony, com um alto desempenho, modular, estável e com várias ferramentas para auxiliar no desempenho, como o Symfony Console."},
    {id:1,color:"#228270",title:"Uma arquitetura simples",info:"16/07" ,content: ''}
];